### ISSUE TITLE
Link BOOL and SEL

### ISSUE THREAD

**Issue by sebastianludwig** [lurado/BetterAppleDocsets#2]
Currently they aren't linked.

**Comment by jlnr** [comment]
More linking errors:

![hyphen bug](https://cloud.githubusercontent.com/assets/70772/25917262/c0c6afce-35c7-11e7-8158-219bc73025e3.png)

![hyphen bug 2](https://cloud.githubusercontent.com/assets/70772/25917245/b276b7fc-35c7-11e7-875a-8b9d049900c9.png)
